vendor!/noam148/yii2-image-manager/controllers/ManagerController.php
<?php

namespace noam148\imagemanager\controllers;

use Yii;
use noam148\imagemanager\models\ImageManager;
use noam148\imagemanager\models\ImageManagerSearch;
use noam148\imagemanager\assets\ImageManagerModuleAsset;
use yii\web\Response;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\base\ErrorException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\helpers\Json;
use yii\helpers\BaseFileHelper;
use yii\imagine\Image;
use Imagine\Image\Box;
use Imagine\Image\Palette\RGB;
use Imagine\Image\Point;
use noam148\imagemanager\Module;

/**
 * Manager controller for the `imagemanager` module
 * @property $module Module
 */
class ManagerController extends Controller {

	/**
	 * @inheritdoc
	 */
	public function behaviors() {
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function beforeAction($action) {
		//disable CSRF Validation
		$this->enableCsrfValidation = false;
		return parent::beforeAction($action);
	}

	/**
	 * Lists all ImageManager models.
	 * @return mixed
	 */
	public function actionIndex() {
        //set asset
		ImageManagerModuleAsset::register($this->view);	
        
		//get iframe parameters
		$viewMode = Yii::$app->request->get("view-mode", "page");
		$selectType = Yii::$app->request->get("select-type", "input");
		$inputFieldId = Yii::$app->request->get("input-id");
		$cropAspectRatio = Yii::$app->request->get("aspect-ratio");
		$cropViewMode = Yii::$app->request->get("crop-view-mode", 1);
		$defaultImageId = Yii::$app->request->get("image-id");
        $news_id = Yii::$app->request->get("news-id");


		//set blank layout if viewMode = iframe
		if ($viewMode == "iframe") {
			//set layout
			$this->layout = "blank";

			//set stylesheet for modal
			$aCssFiles = \Yii::$app->controller->module->cssFiles;
			if (is_array($aCssFiles) && count($aCssFiles) > 0) {
				//if exists loop through files and add them to iframe mode
				foreach ($aCssFiles AS $cssFile) {
					//registrate file
					$this->view->registerCssFile($cssFile, ['depends' => 'yii\bootstrap\BootstrapAsset']);
				}
			}
		}

		//set baseUrl from image manager
		$sBaseUrl = Url::to(['/imagemanager/manager']);
		//set base url
		$this->view->registerJs("imageManagerModule.baseUrl = '" . $sBaseUrl . "';", 3);
        $this->view->registerJs("imageManagerModule.newsId = '" . $news_id . "';", 3);
		$this->view->registerJs("imageManagerModule.defaultImageId = '" . $defaultImageId . "';", 3);
		$this->view->registerJs("imageManagerModule.fieldId = '" . $inputFieldId . "';", 3);
		$this->view->registerJs("imageManagerModule.cropRatio = '" . $cropAspectRatio . "';", 3);
		$this->view->registerJs("imageManagerModule.cropViewMode = '" . $cropViewMode . "';", 3);
		$this->view->registerJs("imageManagerModule.selectType = '" . $selectType . "';", 3);
		$this->view->registerJs("imageManagerModule.message = " . Json::encode([
					'deleteMessage' => Yii::t('imagemanager', 'Are you sure you want to delete this image?'),
				]) . ";", 3);
        $path = \Yii::$app->imagemanager->mediaPath;
        if(!!$news_id){
            $path .= '/'.  $news_id;
        }
        if(!is_dir($path)){
            @mkdir($path);
        }
        $items = @scandir($path);

		//$searchModel = new ImageManagerSearch();
		//$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		//render template
		return $this->render(
						'index', [
                    'news_id'=>$news_id,
					'viewMode' => $viewMode,
					'selectType' => $selectType,
                'items'=>$items,
            'path'=>$path
		]);
	}

	/**
	 * Creates a new ImageManager model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionUpload($news_id = null) {
        //set response header
        Yii::$app->getResponse()->format = Response::FORMAT_JSON;
        // Check if the user is allowed to upload the image
        if (Yii::$app->controller->module->canUploadImage == false) {
            // Return the response array to prevent from the action being executed any further
            return [];
        }
        // Create the transaction and set the success variable
        $transaction = Yii::$app->db->beginTransaction();
        $bSuccess = false;

		//disable Csrf
		Yii::$app->controller->enableCsrfValidation = false;
		//return default
		$return = $_FILES;
		//set media path
        $sMediaPath = \Yii::$app->imagemanager->mediaPath;
        if($news_id != null){
            $sMediaPath .= '/'.$news_id;
        }

		//create the folder
		BaseFileHelper::createDirectory($sMediaPath);

		//check file isset
		if (isset($_FILES['imagemanagerFiles']['tmp_name'])) {
			//loop through each uploaded file
			foreach ($_FILES['imagemanagerFiles']['tmp_name'] AS $key => $sTempFile) {
				//collect variables
				$sFileName = $_FILES['imagemanagerFiles']['name'][$key];
				$sFileExtension = pathinfo($sFileName, PATHINFO_EXTENSION);
				$iErrorCode = $_FILES['imagemanagerFiles']['error'][$key];
				//if uploaded file has no error code  than continue;
				if ($iErrorCode == 0) { 
					//create a file record
                    $mode_filename = str_replace("_", "-", $sFileName);
                    $image_name = explode('.', $mode_filename);
                    $sFiletype = $image_name[1];
                    $image_name = $image_name[0];
                    $model_fileHash = Yii::$app->getSecurity()->generateRandomString(32);
                    $sSaveFileName = $model_fileHash . "." . $sFileExtension;
                    //move_uploaded_file($sTempFile, $sMediaPath."/".$sFileName);
                    //save with Imagine class

                    Image::getImagine()->open($sTempFile)->save($sMediaPath . "/" . $mode_filename);
                   /* if($news_id && is_numeric($news_id)){
                   Image::thumbnail($sMediaPath . "/" . $mode_filename, 250, 250)->save($sMediaPath."/".$image_name."_250_250.".$sFiletype, ['quality' => 85]);
                        Image::thumbnail($sMediaPath . "/" . $mode_filename, 75, 75)->save($sMediaPath."/".$image_name."_75_75.".$sFiletype, ['quality' => 85]);
                        Image::thumbnail($sMediaPath . "/" . $mode_filename, 381, 250)->save($sMediaPath."/".$image_name."_381_250.".$sFiletype, ['quality' => 85]);
                        Image::thumbnail($sMediaPath . "/" . $mode_filename, 400, 300)->save($sMediaPath."/".$image_name."_400_300.".$sFiletype, ['quality' => 85]);
                        Image::thumbnail($sMediaPath . "/" . $mode_filename, 640, 350)->save($sMediaPath."/".$image_name."_640_350.".$sFiletype, ['quality' => 85]);
                    }*/

                    $bSuccess = true;
					/*$model = new ImageManager();

					$model->fileName = str_replace("_", "-", $sFileName);
					$model->fileHash = Yii::$app->getSecurity()->generateRandomString(32);
					//if file is saved add record
					if ($model->save()) {
						//move file to dir
						$sSaveFileName = $model->id . "_" . $model->fileHash . "." . $sFileExtension;
						//move_uploaded_file($sTempFile, $sMediaPath."/".$sFileName);
						//save with Imagine class
						Image::getImagine()->open($sTempFile)->save($sMediaPath . "/" . $sSaveFileName);
						$bSuccess = true;
					}*/

				}
			}
		}

		if ($bSuccess) {
		    // The upload action went successful, save the transaction
		    $transaction->commit();
		} else {
		    // There where problems during the upload, kill the transaction
		    $transaction->rollBack();
		}

		//echo return json encoded
		return $return;
	}

	/**
	 * Crop image and create new ImageManager model.
	 * @return mixed
	 */
	public function actionCrop() {
		//return 
		$return = null;
		//disable Csrf
		Yii::$app->controller->enableCsrfValidation = false;
		//set response header
		Yii::$app->getResponse()->format = Response::FORMAT_JSON;
		//set media path
		$sMediaPath = \Yii::$app->imagemanager->mediaPath;
		//get post
		$ImageManager_id = Yii::$app->request->post("ImageManager_id");
		$aCropData = Yii::$app->request->post("CropData");
		//get details
		$modelOriginal = $this->findModel($ImageManager_id);
		//check if path is not null
		if ($modelOriginal->imagePathPrivate !== null && $aCropData !== null) {
			//dimension
			$iDimensionWidth = round($aCropData['width']);
			$iDimensionHeight = round($aCropData['height']);
			//collect variables
			$sFileNameReplace = preg_replace("/_crop_\d+x\d+/", "", $modelOriginal->fileName);
			$sFileName = pathinfo($sFileNameReplace, PATHINFO_FILENAME);
			$sFileExtension = pathinfo($sFileNameReplace, PATHINFO_EXTENSION);
			$sDisplayFileName = $sFileName . "_crop_" . $iDimensionWidth . "x" . $iDimensionHeight . "." . $sFileExtension;

            //start transaction
            $transaction  = Yii::$app->db->beginTransaction();
            $bCropSuccess = false;
            
			//create a file record
			$model = new ImageManager();
			$model->fileName = $sDisplayFileName;
			$model->fileHash = Yii::$app->getSecurity()->generateRandomString(32);
			//if file is saved add record
			if ($model->save()) {
                
                //do crop in try catch
                try {
                    // create file name
                    $sSaveFileName = $model->id . "_" . $model->fileHash . "." . $sFileExtension;
                    
                    // get current/original image data
                    $imageOriginal = Image::getImagine()->open($modelOriginal->imagePathPrivate);
                    $imageOriginalSize = $imageOriginal->getSize();
                    $imageOriginalWidth = $imageOriginalSize->getWidth();
                    $imageOriginalHeight = $imageOriginalSize->getHeight();
                    $imageOriginalPositionX = 0;
                    $imageOriginalPositionY = 0;
                    

vendor!/noam148/yii2-image-manager/views/manager/_item.php
<div class="thumbnail">
	<img src="<?=\Yii::$app->imagemanager->getImagePath($model->id, 300, 300)?>" alt="<?=$model->fileName?>">
	<div class="filename"><?=$model->fileName?></div>
</div>

vendor!/noam148/yii2-image-manager/views/manager/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use kartik\file\FileInput;

$this->title = Yii::t('imagemanager','Image manager');

?>
<div id="module-imagemanager" class="container-fluid <?=$selectType?>">
	<div class="row">
		<div class="col-xs-6 col-sm-10 col-image-editor">
			<div class="image-cropper">
				<div class="image-wrapper">
					<img id="image-cropper" />
				</div>
				<div class="action-buttons">
					<a href="#" class="btn btn-primary apply-crop">
						<i class="fa fa-crop"></i>
						<span class="hidden-xs"><?=Yii::t('imagemanager','Crop')?></span>
					</a>
					<?php if($viewMode === "iframe"): ?>
					<a href="#" class="btn btn-primary apply-crop-select">
						<i class="fa fa-crop"></i>
						<span class="hidden-xs"><?=Yii::t('imagemanager','Crop and select')?></span>
					</a>
					<?php endif; ?>
					<a href="#" class="btn btn-default cancel-crop">
						<i class="fa fa-undo"></i>
						<span class="hidden-xs"><?=Yii::t('imagemanager','Cancel')?></span>
					</a>
				</div>
			</div> 
		</div>
		<div class="col-xs-6 col-sm-10 col-overview">
			<div class="form-group">

					<?php Pjax::begin([
						'id'=>'pjax-mediamanager',
						'timeout'=>'5000'
					]); ?>


					<div id="w0" class="list-view">
						<div class="item-overview">
						<?php for($i = 2 ; $i < count($items); $i++) { ?>
							<?php if(!is_dir($path.'/'.$items[$i])){ ?>
								<div class="item img-thumbnail" data-key="<?=$items[$i]?>"><div class="thumbnail">
										<img src="<?=$path.'/'.$items[$i]?>" alt="<?=$items[$i]?>">
										<div class="filename"><?=$items[$i]?></div>
									</div>
								</div>
							<?php	}	 ?>


						<?php } ?>
						</div>
					</div>
				<?php Pjax::end(); ?>
			</div>
		</div>
		<div class="col-xs-6 col-sm-2 col-options">


			<?php
				if (Yii::$app->controller->module->canUploadImage):
			?>

			<?=FileInput::widget([
				'name' => 'imagemanagerFiles[]',
				'id' => 'imagemanager-files',
				'options' => [
					'multiple' => true,
					'accept' => 'image/*',
					'news-id'=>$news_id
				],
				'pluginOptions' => [
					'uploadUrl' => Url::to(['manager/upload', 'news_id'=>$news_id]),
					'allowedFileExtensions' => \Yii::$app->controller->module->allowedFileExtensions, 
					'uploadAsync' => false,
					'showPreview' => false,
					'showRemove' => false,
					'showUpload' => false,
					'showCancel' => false,
					'browseClass' => 'btn btn-primary btn-block',
					'browseIcon' => '<i class="fa fa-upload"></i> ',
					'browseLabel' => Yii::t('imagemanager','Upload')
				],
				'pluginEvents' => [
					"filebatchselected" => "function(event, files){  $('.msg-invalid-file-extension').addClass('hide'); $(this).fileinput('upload'); }",
					"filebatchuploadsuccess" => "function(event, data, previewId, index) {
						imageManagerModule.uploadSuccess(data.jqXHR.responseJSON.imagemanagerFiles);
					}",
					"fileuploaderror" => "function(event, data) { $('.msg-invalid-file-extension').removeClass('hide'); }",
				],
			]) ?>

			<?php
				endif;
			?>

			<div class="image-info hide">
				<div class="thumbnail">
					<img src="#">
				</div>
				<!--<div class="edit-buttons">
					<a href="#" class="btn btn-primary btn-block crop-image-item">
						<i class="fa fa-crop"></i>
						<span class="hidden-xs"><?=Yii::t('imagemanager','Crop')?></span>
					</a>
				</div>-->
				<div class="details">
					<div class="fileName"></div>
					<div class="created"></div>
					<div class="fileSize"></div>
					<!--<div class="dimensions"><span class="dimension-width"></span> &times; <span class="dimension-height"></span></div>-->
					<?php
						if (Yii::$app->controller->module->canRemoveImage):
					?>
						<a href="#" class="btn btn-xs btn-danger delete-image-item" ><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <?=Yii::t('imagemanager','Delete')?></a>
					<?php
						endif;
					?>
				</div>
				<?php if($viewMode === "iframe"): ?>
				<a href="#" class="btn btn-primary btn-block pick-image-item"><?=Yii::t('imagemanager','Select')?></a> 
				<?php endif; ?>
			</div>
		</div>  
	</div>
</div>  